### ISSUE TITLE
Usefullness with graphql requests

### ISSUE THREAD

**Issue by NavidMitchell** [knative-extensions/security-guard#315]
Hello I am evaluating knative for a project. I am curious how well security-guard would work if all requests sent to knative services will be graphql requests?

**Comment by davidhadas** [comment]
@NavidMitchell , 
Assuming the security concern you focus on is the use of graphql requests to attack a system, and assuming that the graphql is configured to serve over http, security guard will analyze the graphql json body up to 1M and can detect unexpected keys and the use of suspicious patterns in the values. 

If you expect normal traffic to contain request body with > 1M, note that the current version of security-guard  will analyze request headers but will not analyze >1M request body. 
If you do not expect normal traffic to contain request body with > 1M, security-guard  will analyze request headers + body and will also flag/stop requests with abnormal body size. 

Let me know if you need more information.

**Comment by NavidMitchell** [comment]
That's great! Thank you!

**Comment by davidhadas** [comment]
I am closing this issue  - please reopen if you have more questions on this subject.
